# 🧑‍💻 NumPy Complete Guided Project
**Instructor / Student Colab Notebook** – covers *all* key concepts from `Numpy‑1` to `Numpy‑5`.

*Generated: 08 Aug 2025*


**Table of Contents**

1. [Setup](#setup)  
2. [Array Creation & Dtypes](#creation)  
3. [Array Attributes & Inspection](#attributes)  
4. [Indexing, Slicing, Fancy Indexing](#indexing)  
5. [Reshaping, Transpose & Copies vs Views](#reshape)  
6. [Joining, Splitting, Set & Sorting Ops](#join)  
7. [Arithmetic Ops, Universal Functions](#arithmetic)  
8. [Broadcasting (Rules + Examples)](#broadcast)  
9. [Statistics & Aggregations](#stats)  
10. [Random Numbers & Reproducibility](#random)  
11. [Structured / Recarrays](#structured)  
12. [Linear Algebra Essentials](#linalg)  
13. [File I/O (`npy`, `npz`, `txt`)](#io)  
14. [Datetime64 & Timedelta64](#datetime)  
15. [Masked Arrays & NaNs](#mask)  
16. [Mini‑Project — Fitness Data Analysis](#project)  
17. [Conclusion & Next Steps](#conclusion)  


## <a name='setup'></a>1️⃣ Setup

In [ ]:
import numpy as np, math, os, pathlib, types, textwrap, random
print('NumPy version:', np.__version__)

NumPy version: 2.0.2


## <a name='creation'></a>2️⃣ Array Creation & Dtypes

Key functions: `np.array`, `np.arange`, `np.linspace`, `zeros`, `ones`, `full`, `eye`, `identity`, `diag`, `empty`

In [ ]:
# EXAMPLE
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.linspace(0, 1, 6)
arr3 = np.full((2,3), 7.5)
print(arr1, arr2, arr3, sep="\n")
print("dtypes:", arr1.dtype, arr2.dtype)


[1 2 3]
[0.  0.2 0.4 0.6 0.8 1. ]
[[7.5 7.5 7.5]
 [7.5 7.5 7.5]]
dtypes: int32 float64


In [ ]:
# 🖊️ TODO: create a 10×10 chessboard pattern using zeros & ones
arr1=np.full((10,10),(0))
arr1[1::2,::2]=1
arr1[::2,1::2]=1
print(arr1)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


## <a name='attributes'></a>3️⃣ Array Attributes & Inspection

`shape`, `ndim`, `size`, `dtype`, `itemsize`, `nbytes`

In [ ]:
M = np.arange(12).reshape(3,4)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


shape (3, 4) ndim 2 size 12 itemsize 8 total bytes 96


In [15]:
# 🖊️ TODO: check memory footprint of a 1000×1000 float64 array
a=np.arange(1000000).reshape(1000,1000)
print('shape', a.shape, 'ndim', a.ndim, 'size', a.size, 'itemsize', a.itemsize, 'total bytes', a.nbytes)


shape (1000, 1000) ndim 2 size 1000000 itemsize 8 total bytes 8000000


## <a name='indexing'></a>4️⃣ Indexing, Slicing & Fancy Indexing

In [ ]:
a = np.arange(1,26).reshape(5,5)
print(a[:, 0])     # first column
print(a[::2, ::2]) # every 2nd row/col
mask = (a % 3 == 0)
print('multiples of 3:', a[mask])


[ 1  6 11 16 21]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
multiples of 3: [ 3  6  9 12 15 18 21 24]


In [16]:
# 🖊️ TODO: use fancy indexing to swap first and last rows of `a`
a= np.arange(1,26).reshape(5,5)
a[[0, -1], :] = a[[-1, 0], :]

print(a)

[[21 22 23 24 25]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1  2  3  4  5]]


## <a name='reshape'></a>5️⃣ Reshaping, Transpose & Copies vs Views

In [ ]:
b = np.arange(8)
B = b.reshape(2,4)
B[0,0] = 99
print('b is modified:', b)
C = b.reshape(2,4).copy()
C[0,0] = -1
print('b unchanged with copy:', b)


b is modified: [99  1  2  3  4  5  6  7]
b unchanged with copy: [99  1  2  3  4  5  6  7]


In [21]:
# 🖊️ TODO: Flatten a 3‑D array into 1‑D using both `ravel` and `flatten`; observe copy vs view.
a = np.arange(24).reshape(2, 3, 4)
print(a)
r = a.ravel()
print(r)
f = a.flatten()
print(f)
r[0] = 1000
print(a)
f[1] = 999
print(a)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[1000    1    2    3]
  [   4    5    6    7]
  [   8    9   10   11]]

 [[  12   13   14   15]
  [  16   17   18   19]
  [  20   21   22   23]]]
[[[1000    1    2    3]
  [   4    5    6    7]
  [   8    9   10   11]]

 [[  12   13   14   15]
  [  16   17   18   19]
  [  20   21   22   23]]]


## <a name='join'></a>6️⃣ Joining, Splitting, Set & Sorting Ops

In [ ]:
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print('union', np.union1d(x,y))
print('intersect', np.intersect1d(xy,[1,2,10]))
print('sorted descending', np.sort(xy)[::-1])


In [24]:
# 🖊️ TODO: split `xy` back into two equal halves using `np.array_split`
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
parts = np.array_split(xy, 2)
print(parts[0])
print(parts[1])

[1 3 5]
[2 4 6]


## <a name='arithmetic'></a>7️⃣ Arithmetic Ops & Universal Functions

In [ ]:
v = np.arange(5)
print('exp', np.exp(v))
print('sin', np.sin(v))
print('vectorised addition', v + 10)


exp [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
sin [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
vectorised addition [10 11 12 13 14]


In [25]:
# 🖊️ TODO: given degrees [0,30,45,60,90], compute radians and sin values.

deg = np.array([0, 30, 45, 60, 90])
rad = np.deg2rad(deg)
sin_vals = np.sin(rad)

print("Radians:", rad)
print("Sine:", sin_vals)


Radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine: [0.         0.5        0.70710678 0.8660254  1.        ]


## <a name='broadcast'></a>8️⃣ Broadcasting Rules

Rules: compare dimensions from right → left; stretch size 1 dims; mismatch error.

In [ ]:
row = np.arange(5)
col = np.arange(3).reshape(3,1)
matrix = row + col  # broadcast to 3×5
print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]]


In [ ]:
# 🖊️ TODO: use broadcasting to create a 10×10 multiplication table.
row=np.arange(1,11)
col=np.arange(1,11).reshape(10,1)
matrix=row*col
print(matrix)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## <a name='stats'></a>9️⃣ Statistics & Aggregations

In [ ]:
data = np.random.default_rng(0).integers(1, 100, size=(5,4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))


In [30]:
# 🖊️ TODO: compute `np.percentile` (25th, 50th, 75th) of flattened `data`.
dt = np.random.default_rng(0).integers(1, 100, size=(5,4))
data = dt.flatten()
print(np.percentile(data,25))
print(np.percentile(data,50))
print(np.percentile(data,75))


30.0
58.5
75.0


## <a name='random'></a>🔟 Random Numbers & Reproducibility

In [ ]:
rng = np.random.default_rng(42)
rand_floats = rng.random(5)
rand_ints = rng.integers(low=10, high=50, size=5)
print(rand_floats, rand_ints)
rng2 = np.random.default_rng(42)
assert np.allclose(rand_floats, rng2.random(5))


In [31]:
# 🖊️ TODO: simulate rolling a fair six‑sided die 100 times; estimate proportion of 6s.
rolls = np.random.default_rng(0).integers(1,7, size = 100)
print(rolls)
print(np.mean(rolls == 6))



[6 4 4 2 2 1 1 1 2 5 4 6 4 4 6 5 4 4 4 6 2 5 5 1 3 6 4 1 5 5 6 2 1 6 1 4 1
 2 3 3 3 1 1 1 1 5 4 4 2 4 5 3 3 6 5 6 3 5 6 4 6 5 5 3 6 1 4 5 6 4 3 2 3 3
 5 6 1 6 4 3 5 4 2 2 5 4 4 3 5 3 2 6 2 2 5 4 1 1 3 5]
0.16


## <a name='structured'></a>1️⃣1️⃣ Structured / Record Arrays

In [ ]:
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                   dtype=[('name','U10'), ('age','i4'), ('weight','f4')])
print(people['name'], people['age'].mean())


['Alice' 'Bob'] 27.5


In [ ]:
# 🖊️ TODO: add a new field 'height' to the structured array using `np.lib.recfunctions.append_fields` (hint: pip install?).
import numpy as np
from numpy.lib import recfunctions as rfn

people = np.array(
    [('Alice', 25, 55.0), ('Bob', 30, 85.5)],
    dtype=[('name','U10'), ('age','i4'), ('weight','f4')]
)
print(people['name'], people['age'].mean())

heights = [162.0, 175.0]
people_with_height = rfn.append_fields(people, 'height', heights)
print(people_with_height)


['Alice' 'Bob'] 27.5
[('Alice', 25, 55.0, 162.0) ('Bob', 30, 85.5, 175.0)]


## <a name='linalg'></a>1️⃣2️⃣ Linear Algebra Essentials

In [33]:
A = np.random.random((3,3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))


A·x ≈ b? True


In [32]:
# 🖊️ TODO: compute eigenvalues of `A` using `np.linalg.eig`.
A = np.random.random((3,3))
eigenvalues, eigenvectors = np.linalg.eig(A)
print('eigenvalues:', eigenvalues)
print('eigenvectors:', eigenvectors)


eigenvalues: [ 1.2667774 +0.j         -0.12014059+0.23375461j -0.12014059-0.23375461j]
eigenvectors: [[ 0.47213949+0.j          0.67153129+0.j          0.67153129-0.j        ]
 [ 0.54896646+0.j         -0.3835244 -0.29300277j -0.3835244 +0.29300277j]
 [ 0.68972468+0.j         -0.48758954+0.2799296j  -0.48758954-0.2799296j ]]


## <a name='io'></a>1️⃣3️⃣ File I/O (`npy`, `npz`, `txt`)

In [ ]:
np.save('array.npy', A)
loaded = np.load('array.npy')
print('loaded equals A?', np.allclose(loaded, A))
np.savez('multi_arrays.npz', A=A, b=b)


NameError: name 'A' is not defined

In [3]:
# 🖊️ TODO: Use `np.savetxt` to write `data` (from stats section) to CSV then reload with `np.loadtxt`.
import numpy as np

data = np.array([
    [86, 15, 75, 88],
    [24, 46, 56, 22],
    [13, 43, 41,  6],
    [ 2, 99,  6, 87],
    [61, 94,  2, 92]
])


np.savetxt('data.csv', data, delimiter=',', fmt='%d')

loaded = np.loadtxt('data.csv', delimiter=',', dtype=int)

print("Original data:\n", data)
print("\nReloaded data:\n", loaded)

Original data:
 [[86 15 75 88]
 [24 46 56 22]
 [13 43 41  6]
 [ 2 99  6 87]
 [61 94  2 92]]

Reloaded data:
 [[86 15 75 88]
 [24 46 56 22]
 [13 43 41  6]
 [ 2 99  6 87]
 [61 94  2 92]]


## <a name='datetime'></a>1️⃣4️⃣ Datetime64 & Timedelta64

In [ ]:
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])


In [5]:
# 🖊️ TODO: find how many Mondays appear in `dates` array.
import numpy as np

dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
mondays = np.sum(dates.astype('datetime64[D]').astype(int) % 7 == 0)
print("Total mondays:", mondays)


Total mondays: 13


## <a name='mask'></a>1️⃣5️⃣ Masked Arrays & NaNs

In [ ]:
arr = np.array([1, 2, np.nan, 4, np.nan])
masked = np.ma.masked_invalid(arr)
print(masked.mean())


In [6]:
# 🖊️ TODO: replace NaNs with column means in a 2‑D array containing NaNs.
import numpy as np

arr = np.array([[1, np.nan, 3],
                [4, 5, np.nan],
                [7, 8, 9]])

col_means = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_means, inds[1])
print("Array after replacing NaNs with column means:\n",arr)


Array after replacing NaNs with column means:
 [[1.  6.5 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


## <a name='project'></a>1️⃣6️⃣ Mini‑Project: Fitness Data Analysis

Load `fitness.txt` (tab‑separated) then follow prompts.

In [ ]:
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))


In [11]:
# 🖊️ TODO: Monthly step count, sleep vs mood correlation, weekly summary, etc.
import numpy as np

with open('/content/fitness.txt', encoding='utf-8') as f:
    data = [line.split() for line in f.readlines()[2:] if line.strip()]

dates = np.array([f"{d[6:]}-{d[3:5]}-{d[:2]}" for d, *_ in data], 'datetime64[D]')
steps = np.array([s for _, s, *_ in data], int)
mood = np.array([m for *_, m, _ in data], float)
sleep = np.array([s for *_, s in data], float)

print("Monthly step counts:")
for m in np.unique(dates.astype('datetime64[M]')):
    print(m, steps[dates.astype('datetime64[M]') == m].sum())

print("\nSleep vs Mood correlation:", np.corrcoef(sleep, mood)[0, 1])

print("\nWeekly summary:")
for w in np.unique(dates.astype('datetime64[W]')):
    mask = dates.astype('datetime64[W]') == w
    print(w,
          "Steps:", steps[mask].sum(),
          "Avg Mood:", round(mood[mask].mean(), 1),
          "Avg Sleep:", round(sleep[mask].mean(), 1))

Monthly step counts:
2023-01 208700
2023-02 202600
2023-03 236000

Sleep vs Mood correlation: 0.9693697299271407

Weekly summary:
2022-12-29 Steps: 23500 Avg Mood: 7.4 Avg Sleep: 7.0
2023-01-05 Steps: 46400 Avg Mood: 7.7 Avg Sleep: 7.5
2023-01-12 Steps: 47600 Avg Mood: 7.8 Avg Sleep: 7.6
2023-01-19 Steps: 48300 Avg Mood: 7.9 Avg Sleep: 7.7
2023-01-26 Steps: 48500 Avg Mood: 8.0 Avg Sleep: 7.8
2023-02-02 Steps: 49700 Avg Mood: 8.1 Avg Sleep: 7.9
2023-02-09 Steps: 50400 Avg Mood: 8.2 Avg Sleep: 8.0
2023-02-16 Steps: 51100 Avg Mood: 8.3 Avg Sleep: 8.1
2023-02-23 Steps: 51800 Avg Mood: 8.4 Avg Sleep: 8.2
2023-03-02 Steps: 52500 Avg Mood: 8.5 Avg Sleep: 8.3
2023-03-09 Steps: 53200 Avg Mood: 8.6 Avg Sleep: 8.4
2023-03-16 Steps: 53900 Avg Mood: 8.7 Avg Sleep: 8.5
2023-03-23 Steps: 54600 Avg Mood: 8.8 Avg Sleep: 8.6
2023-03-30 Steps: 15800 Avg Mood: 8.9 Avg Sleep: 8.7


## <a name='conclusion'></a>1️⃣7️⃣ Conclusion & Further Practice
Congrats on covering **all core NumPy topics** from your five lecture notebooks!

*Keep experimenting, read the official docs, and try converting your NumPy pipelines into Pandas or JAX for more fun.*